name: Ollama Code Review

# 상단에 환경 변수 설정
env:
  # 서버 설정
  OLLAMA_IP: "10.11.10.83"
  OLLAMA_MODEL: "llama2:3b"
  REQUEST_TIMEOUT: 600  # 타임아웃 시간(초)
  
  # 파일 설정
  FILE_EXTENSIONS: ".java"  # 리뷰할 파일 확장자
  
  # 리뷰 프롬프트 설정 - 실제 사용할 간단한 프롬프트
  REVIEW_ASPECTS: |
    Please only review if the class name is appropriate for its purpose.
    Response should be a single sentence either approving or suggesting a better name.
  
  # 원래 프롬프트 (주석처리)
  # REVIEW_ASPECTS: |
  #   1. Code quality and Java best practices
  #   2. Potential bugs or logical errors
  #   3. Performance considerations
  #   4. Clean code principles
  #   5. Design patterns usage
  #   6. Security concerns
  
  # 간단한 포맷
  REVIEW_FORMAT: |
    Class name review: [Your one-sentence response]
  
  # 원래 포맷 (주석처리)
  # REVIEW_FORMAT: |
  #   ## Summary
  #   [Brief overview of the code]
  #   
  #   ## Key Findings
  #   [Main points and issues]
  #   
  #   ## Recommendations
  #   [Specific suggestions for improvement]

[이하 코드는 동일하게 유지...]
